### ISSUE TITLE
Authenticate Not Working After Updating Environment Variables

### ISSUE THREAD

**Issue by celery9376** [TCGplayer/Postman-Api#2]
I'm receiving a "invalid_grant" error when trying to run "Authenticate" included within the TCGPlayer.postman_collection.json.

I've followed the instructions and have updated the TCGPlayer environment variables like follows:

publicId: {Public Key sent to me in email}
privateId: {Private Key sent to me in email}
accessToken: {Tried with and without the Access Token sent to me in email}

I have not used the Application ID sent to me in email.

Do I have something configured incorrectly?

**Comment by celery9376** [comment]
The X-Tcg-Access-Token field had to be set as well for Authenticate to work

**Comment by aruku** [comment]
I didn´t receive the Access Token in my email, and after several tries I had to remove that header from the request for it to work.
